
--MERGE generated by 'sp_generate_merge' stored procedure, Version 0.93
--Originally by Vyas (http://vyaskn.tripod.com): sp_generate_inserts (build 22)
--Adapted for SQL Server 2008/2012 by Daniel Nolan (http://danere.com)

SET NOCOUNT ON

SET IDENTITY_INSERT [Role] ON

MERGE INTO [Role] AS Target
USING (VALUES
  (1,'Employee')
 ,(2,'Supervisor')
) AS Source ([RoleId],[RoleName])
ON (Target.[RoleId] = Source.[RoleId])
WHEN MATCHED AND (
	NULLIF(Source.[RoleName], Target.[RoleName]) IS NOT NULL OR NULLIF(Target.[RoleName], Source.[RoleName]) IS NOT NULL) THEN
 UPDATE SET
  [RoleName] = Source.[RoleName]
WHEN NOT MATCHED BY TARGET THEN
 INSERT([RoleId],[RoleName])
 VALUES(Source.[RoleId],Source.[RoleName])
WHEN NOT MATCHED BY SOURCE THEN 
 DELETE
;
GO
DECLARE @mergeError int
 , @mergeCount int
SELECT @mergeError = @@ERROR, @mergeCount = @@ROWCOUNT
IF @mergeError != 0
 BEGIN
 PRINT 'ERROR OCCURRED IN MERGE FOR [Role]. Rows affected: ' + CAST(@mergeCount AS VARCHAR(100)); -- SQL should always return zero rows affected
 END
ELSE
 BEGIN
 PRINT '[Role] rows affected by MERGE: ' + CAST(@mergeCount AS VARCHAR(100));
 END
GO

SET IDENTITY_INSERT [Role] OFF
GO
SET NOCOUNT OFF
GO
